# Thông tin c?u hình database XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/csms_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# C?u hình Hibernate t? ??ng t?o/c?p nh?t b?ng t? code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# (?ã xóa dòng dialect c? gây l?i)